/**
 * 字段名 → 中文 label 字典。
 *
 * 由 detail.vue 迁移至此（2026-08-05）。覆盖：
 * - 基础 / anon 主键 / 就诊 / 手术 / 检验结果 / 医嘱 / 检查 + 报告 + detail
 * - 历史跨阶段保留字段（med_* 兼容）
 *
 * 扩充（2026-08-05）：新增病史 / 病案首页 / 人口学常用键，
 * 用于 KeyValueCard 在没有 schema.labelMap 时也能给出中文 label。
 */

export const FIELD_LABELS: Record<string, string> = {
  // ───── 模态分类 ─────
  clinical: "就诊",
  surgery: "手术",
  order: "医嘱",
  collection: "检查",
  genetic: "基因检测",
  pathology: "病理",
  ihc: "免疫组化",
  ct: "CT",
  radiology: "影像",
  ultrasound: "超声",

  // ───── 患者 / 基础 ─────
  patient_id: "患者编号",
  center_code: "中心编码",
  source_center: "来源中心",
  sex: "性别",
  age: "年龄",
  age_bucket: "年龄",
  birth_date: "出生日期",
  ethnicity: "民族",
  native_place: "籍贯",
  birth_place: "出生地",
  birthplace: "出生地",
  birth_province: "出生省",
  abo_blood_type: "ABO血型",
  abo_blood_type_frontpage: "ABO血型(首页)",
  rh_blood_type: "RH血型",
  rh_blood_type_frontpage: "RH血型(首页)",
  smoking_status: "吸烟状态",
  first_nodule_date: "首结节日期",
  bmi: "BMI",
  education: "学历",
  income: "收入",
  insurance: "医保",
  address: "地址",
  occupation: "职业",
  marital_status: "婚姻状况",

  // patient.visit_counts（就诊次数统计）
  visit_counts: "就诊次数统计",
  outpatient_count: "门诊次数",
  visit_count: "就诊总次数",

  // patient.medical_history（珠江-新桥病史结构）
  smoking_pack_years: "吸烟包年",
  family_lung_cancer: "一级亲属肺癌史",
  family_other_cancer: "一级亲属其他癌史",
  family_other_cancer_type: "其他癌瘤种",
  prior_malignancy: "既往恶性肿瘤史",
  comorbid_copd: "合并COPD/慢支",
  comorbid_old_tb: "合并陈旧性肺结核",
  discovery_route: "发现途径",

  // ───── 主键 / 编号 ─────
  visit_id: "就诊编号",
  anon_visit_id: "就诊编号",
  exam_id: "检查编号",
  exam_method: "检查方法",
  anon_exam_id: "检查编号",
  visit_ordinal: "就诊序号",
  inpatient_no: "住院号",
  outpatient_no: "门诊号",
  session_id: "会话编号",
  observation_id: "观测项ID",
  record_id: "记录编号",
  item_id: "子项编号",
  request_id: "申请单号",
  case_no: "病案序号",
  original_patient_id: "原始患者编号",
  prescription_id: "处方编号",

  // ───── 就诊 / visit_record ─────
  visit_category: "就诊类别",
  admission_time: "入院(就诊)时间",
  discharge_date: "出院日期",
  admission_dept: "入院(就诊)科室",
  discharge_dept: "出院科室",
  length_of_stay: "住院天数",
  los_days: "住院天数",
  payment_method: "支付方式",
  visit_age: "就诊年龄",
  visit_detail_json: "就诊详情(JSONB)",
  department: "住院科室",
  admission_date: "入院日期",

  // inpatient_front_page（病案首页扩展）
  inpatient_front_page: "住院病案首页",
  admission_route: "入院途径",
  admission_status: "入院状态",
  discharge_method: "离院方式",
  readmit_plan_31d: "31天内再入院计划",
  readmission_31d_planned: "31天再入院计划",
  readmit_purpose: "31天再住院目的",
  readmission_31d_purpose: "31天再住院目的",
  admission_count: "住院次数",
  inpatient_count: "住院次数",
  neonatal_birth_weight: "新生儿出生体重(g)",
  neonatal_admission_weight: "新生儿入院体重(g)",
  newborn_birth_weight_g: "新生儿出生体重(g)",
  newborn_admit_weight_g: "新生儿入院体重(g)",
  post_surgical_complication: "是否术后并发症",
  is_postop_complication: "是否术后并发症",

  // transfusion / transfusion_units 输血史
  transfusion: "输血史",
  transfusion_units: "输血量(单位)",
  whole_blood: "全血",
  rbc: "红细胞",
  plasma: "血浆",
  platelet: "血小板",
  other: "其他",

  // coma_duration / cranial_injury_observation 昏迷时间
  coma_duration: "昏迷时间",
  cranial_injury_observation: "颅脑损伤昏迷观察",
  pre_admission: "入院前",
  post_admission: "入院后",
  pre_admit_days: "入院前(天)",
  pre_admit_hours: "入院前(小时)",
  pre_admit_minutes: "入院前(分钟)",
  post_admit_days: "入院后(天)",
  post_admit_hours: "入院后(小时)",
  post_admit_minutes: "入院后(分钟)",
  days: "天",
  hours: "小时",
  minutes: "分钟",

  rescue_count: "抢救次数",
  rescue_success_count: "抢救成功次数",
  nursing_days: "护理天数",
  level_1: "一级护理天数",
  level_2: "二级护理天数",
  primary_nursing_days: "一级护理天数",
  secondary_nursing_days: "二级护理天数",

  // ───── 手术 ─────
  surgery_id: "手术编号",
  surgery_date: "手术日期",
  surgery_name: "手术名称",
  procedure_name: "术式",
  resection_scope: "切除范围",
  surgical_approach: "手术入路",
  procedure_detail: "手术详情",
  // procedure_detail — 省医结构
  procedure_level: "手术等级",
  incision_healing: "切口愈合等级",
  anesthesia_method: "麻醉方式",
  surgeon: "术者",
  anesthesiologist: "麻醉医生",
  assistant_1: "Ⅰ助",
  assistant_2: "Ⅱ助",
  // procedure_detail — 珠江-新桥结构
  icd9cm3_code: "ICD9-CM3编码",
  ln_dissection_strategy: "淋巴结清扫策略",
  dissected_ln_groups: "清扫淋巴结组别",
  duration_minutes: "手术时长(分钟)",
  asa_score: "ASA评分",
  asa_level: "ASA分级",
  blood_loss_ml: "出血量(ml)",
  complications: "术后并发症",

  // ───── 病理标本 pathology_specimen ─────
  specimen_id: "标本号",
  specimen_name: "标本名称",
  specimen_type: "标本类型",
  specimen_meta: "标本元数据",
  submission_date: "送检日期",
  report_date: "报告日期",
  sampling_site: "取材部位",
  histology_class: "组织学分类",
  pathology_diagnosis: "病理诊断",
  tumor_total_size_mm: "肿瘤大小(mm)",
  gross_findings: "肉眼所见",
  microscopic_findings: "镜下所见",
  immunohistochemistry: "免疫组化",
  special_markers: "特殊检查标志",
  remarks: "备注",
  // specimen_meta — 珠江-新桥结构
  frozen: "冰冻/石蜡",
  paired_specimen_id: "配对标本号",
  multi_nodule_same_report: "多结节同份报告",
  // adenocarcinoma_subtypes 腺癌亚型
  adenocarcinoma_subtypes: "腺癌亚型",
  lepidic_pct: "贴壁型(%)",
  acinar_pct: "腺泡型(%)",
  papillary_pct: "乳头型(%)",
  micropapillary_pct: "微乳头型(%)",
  solid_pct: "实性型(%)",
  major_subtype: "主要亚型",
  rare_subtype: "罕见亚型",
  // tumor_measurement 肿瘤测量
  tumor_measurement: "肿瘤测量",
  differentiation: "分化程度",
  invasive_size_mm: "浸润大小(mm)",
  // high_risk_factors 高危因素
  high_risk_factors: "高危因素",
  stas: "气腔播散(STAS)",
  lymphovascular_invasion: "脉管侵犯(LVI)",
  perineural_invasion: "神经侵犯(PNI)",
  pleural_invasion: "胸膜侵犯",
  // staging 病理分期
  staging: "分期",
  lymph_nodes_positive_total: "淋巴结(阳性/总数)",
  sampled_ln_groups: "送检淋巴结组别",
  positive_ln_groups: "阳性淋巴结组别",
  pt: "病理pT",
  pn: "病理pN",
  pm: "病理pM",
  staging_edition: "分期版本",

  // ───── 检验结果 lab_result ─────
  lab_result_id: "检验编号",
  report_id: "报告号",
  test_name: "检验项目",
  item_name: "检验项",
  item_result: "结果",
  item_result_value: "数值结果",
  item_value: "测量值",
  item_unit: "单位",
  unit: "单位",
  value: "数值",
  ref_lower: "参考下限",
  ref_upper: "参考上限",
  collection_time: "采集时间",
  lab_detail_json: "检验详情(JSONB)",
  test_detail: "检验扩展",
  overall_result: "整体结果",

  // ───── 医嘱（drug_order / non_drug_order） ─────
  order_id: "医嘱编号",
  order_type: "医嘱类型",
  order_name: "医嘱名称",
  order_time: "医嘱时间",
  order_start_time: "医嘱开始时间",
  order_stop_time: "医嘱停止时间",
  stop_time: "停止时间",
  order_source: "医嘱来源",
  order_detail_json: "医嘱详情(JSONB)",
  order_detail: "医嘱详情",
  order_dept: "开嘱科室",
  prescribing_dept: "开立科室",
  duration_type: "长临性质",
  // 药物医嘱 order_detail — 住院
  drug_code: "药物编码",
  drug_trade_name: "药物商品名",
  drug_generic_name: "药物通用名",
  drug_type: "药品类型",
  specification: "药物规格",
  dose: "药物剂量",
  dose_unit: "剂量单位",
  dose_per_use: "使用次剂量",
  frequency: "用药频率",
  route: "用药途径",
  dosage_form: "药物剂型",
  // 药物医嘱 order_detail — 门诊处方
  duration_days: "用药天数",
  prescription_date: "处方开立日期",
  doctor_signature: "开立医生签名",

  // ───── 检查 + 报告 + detail ─────
  exam_type: "检查类型",
  exam_date: "检查日期",
  exam_name: "检查名称",
  exam_body_part: "检查部位",
  body_part: "检查部位",
  exam_item: "检查项目",
  exam_detail: "检查详情",
  type_code: "检查类型代码",
  findings: "检查所见",
  impression: "印象/提示",
  items: "子项列表",
  data_source: "数据来源",
  ultrasound_finding: "超声提示",
  body_clean: "报告正文",
  pii_replaced_count: "已替换 PII 数",
  review_status: "审核状态",
  detail_type: "详情类型",
  detail_ordinal: "详情序号",
  detail_json: "检查详情(JSONB)",

  // ───── 诊断 / 诊断事件 diagnosis 表 ─────
  diagnoses: "诊断",
  diagnosis_source: "诊断来源",
  diagnosis_front_page_meta: "首页诊断扩展",
  diagnosis_no: "诊断次序",
  diagnosis_code: "诊断编码",
  diagnosis_name: "诊断名称",
  diagnosis_type: "诊断类型",
  diagnosis_outcome: "诊断归转",
  diagnosis_category: "诊断类别",
  diagnosis_date: "诊断日期",
  is_primary_diagnosis: "是否主诊断",
  // diagnoses[] 通用子键
  code: "诊断编码",
  name: "诊断名称",
  type: "类型",
  category: "类别",
  is_primary: "是否主诊断",
  outcome: "转归",
  admission_condition: "入院病情",

  // ───── 临床文档 / 病程 progress_note 表 ─────
  clinical_documents: "临床文档",
  progress_note: "病程记录",
  note_id: "文档编号",
  note_type: "文档类型",
  note_date: "记录日期",
  doc_type: "文档类型",
  content: "内容",
  record_date: "记录日期",
  source_document: "来源文档",

  // ───── 病史 medical_history 表 ─────
  medical_history: "既往病史",
  marriage_history: "婚育史",
  marital_history: "婚育史",
  chief_complaint: "主诉",
  present_illness: "现病史",
  past_history: "既往史",
  personal_history: "个人史",
  family_history: "家族史",
  allergic_history: "过敏史",
  allergy: "过敏史",
  operation_history: "手术史",
  physical_exam: "体格检查",
  auxiliary_exam: "辅助检查",
  discharge_diagnosis: "出院诊断",

  // ───── 护理 nursing_observation / ICU icu_observation ─────
  nursing_observation: "护理观察",
  nursing_meta: "护理扩展元数据",
  item_code: "项目编码",
  item_category: "项目类型",
  measurement_time: "测量时间",
  measurement_method: "测量方法",
  nurse_signature: "护士签名",
  icu_observation: "ICU观察项",
  diagnosis_summary: "诊断汇总",
  icu_in_time: "入ICU时间",
  icu_out_time: "出ICU时间",
  weight_kg: "体重(kg)",

  // ───── 麻醉 anesthesia_event 表 ─────
  anesthesia_event: "麻醉事件",
  anesthesia_extra: "麻醉扩展",
  event_type: "事件类型",
  event_time: "事件时间",
  surgery_start_time: "手术开始时间",
  surgery_end_time: "手术结束时间",
  anesthesia_start_time: "麻醉开始时间",
  anesthesia_end_time: "麻醉结束时间",
  room_in_time: "入室时间",
  room_out_time: "出室时间",
  drug_name: "用药名称",
  drug_dose: "用药剂量",
  observation_name: "观察项目",
  observation_value: "观察值",
  observation_unit: "观察单位",

  // ───── 人口学（patient_meta.demographics） ─────
  demographics: "人口学",

  // ───── 基因检测 genetic_test ─────
  genetic_test: "基因检测",
  test_id: "检测号",
  test_date: "检测日期",
  variant_type: "变异类型",
  test_method: "检测方法",
  test_meta: "检测元数据",
  gene_name: "基因名称",
  sample_source: "检测样本来源",
  method: "检测方法",
  raw_text: "原始数据",
  panel_size: "Panel基因数",
  variant_result: "变异结果",
  variant_desc: "变异描述",
  vaf_pct: "变异丰度(%)",
  clinical_significance: "临床意义",
  drug_reference: "用药参考",
  // driver_mutations 驱动基因
  driver_mutations: "驱动基因",
  egfr: "EGFR",
  egfr_vaf_pct: "EGFR丰度(VAF%)",
  kras: "KRAS",
  kras_vaf_pct: "KRAS丰度(VAF%)",
  alk_fusion: "ALK融合",
  ros1_fusion: "ROS1融合",
  ret_fusion: "RET融合",
  ntrk_fusion: "NTRK融合",
  braf: "BRAF",
  her2: "HER2",
  met: "MET",
  tp53: "TP53",
  other_variants: "其他临床意义变异",
  // immune_markers 免疫标志物
  immune_markers: "免疫标志物",
  tmb_per_mb: "TMB(突变/Mb)",
  tmb_level: "TMB分级",
  msi: "MSI",
  mmr: "MMR",

  // ───── 结节影像 nodule_imaging（珠江-新桥） ─────
  nodule_imaging: "结节影像",
  nodule_no: "结节编号",
  nodule_location: "结节位置",
  long_diameter: "长径(mm)",
  density_type: "密度类型",
  exam_meta: "检查元数据",
  contrast: "是否增强",
  slice_thickness_mm: "层厚(mm)",
  // nodule_morphology 形态征象
  nodule_morphology: "形态征象",
  subpleural: "胸膜下",
  margin: "边缘",
  signs: "影像征象",
  mediastinal_lymphadenopathy: "纵隔/肺门淋巴结肿大",
  pleural_effusion: "胸腔积液",
  // nodule_quantitative 定量参数
  nodule_quantitative: "定量参数",
  short_diameter: "短径(mm)",
  volume_mm3: "体积(mm³)",
  mean_ct_value_hu: "平均CT值(HU)",
  solid_ratio_pct: "实性占比(%)",
  solid_component_mm: "实性成分大小(mm)",
  lung_rads: "Lung-RADS",
  dicom_slice: "DICOM切片号",
  follow_up_comparison: "对比变化",
  vs_prior: "与既往片对比",

  // ───── 免疫组化 ihc_result markers（珠江-新桥） ─────
  ihc_result: "免疫组化结果",
  ki67_pct: "Ki-67(%)",
  markers: "标志物",
  pdl1_tps_pct: "PD-L1 TPS(%)",
  pdl1_clone: "PD-L1克隆号",
  pdl1_cps: "PD-L1 CPS",
  alk_ihc: "ALK(IHC)",
  ttf1: "TTF-1",
  napsina: "NapsinA",
  p40: "P40",
  p53: "P53",

  // ───── 随访 follow_up（珠江-新桥） ─────
  follow_up: "随访",
  last_followup_date: "末次随访日期",
  recurrence: "是否复发",
  survival_status: "生存状态",
  // treatment_detail
  treatment_detail: "辅助治疗详情",
  adjuvant_therapy: "辅助治疗",
  first_line_regimen: "一线治疗方案",
  // recurrence_detail
  recurrence_detail: "复发详情",
  recurrence_date: "复发日期",
  recurrence_site: "复发部位",
  death_date: "死亡日期",
};

/** 取字段中文 label，未命中回退为原 key。 */
export function getFieldLabel(key: string): string {
  return FIELD_LABELS[key] || key;
}
